name: todolist
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # navigation
  go_router: ^14.2.1

  # storage
  shared_preferences: ^2.2.3

  # unique uuid gen
  uuid: ^4.4.2

  # dependency injection
  get_it: ^7.7.0

  # state management
  flutter_bloc: ^8.1.6

  # rest
  dio: ^5.5.0+1
#  http_parser: ^4.1.0

  # responsiveness:
  responsive_sizer: ^3.3.1

  # toast lib, pop
  bot_toast: ^4.1.3

  # fonts
  google_fonts: ^6.2.1

  # logs
  fimber: ^0.7.0
  pretty_dio_logger: ^1.4.0

  # skeletons
  shimmer: ^3.0.0

  # sliding panel
#  flutter_sliding_box: ^1.1.5
  sliding_up_panel: ^2.0.0+1

  collection: ^1.18.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.19.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
